{{- if .Values.kubetaskConfig.create }}
apiVersion: kubetask.io/v1alpha1
kind: KubeTaskConfig
metadata:
  name: default
  namespace: {{ include "kubetask.namespace" . }}
  labels:
    {{- include "kubetask.labels" . | nindent 4 }}
spec:
  {{- if .Values.kubetaskConfig.systemImage }}
  systemImage:
    {{- if .Values.kubetaskConfig.systemImage.image }}
    image: {{ .Values.kubetaskConfig.systemImage.image | quote }}
    {{- end }}
    {{- if .Values.kubetaskConfig.systemImage.imagePullPolicy }}
    imagePullPolicy: {{ .Values.kubetaskConfig.systemImage.imagePullPolicy }}
    {{- end }}
  {{- end }}
{{- end }}
