# Copyright Contributors to the KubeTask project
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubetask-dogfooding

resources:
  - namespace.yaml
  - rbac.yaml
  - secrets.yaml
  - agent-default.yaml
  - agent-dev-realtime.yaml
  - context-basic-rules.yaml
  - configmap-github-scripts.yaml
  - context-github-app-auth.yaml
  - context-github-scripts.yaml
