apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeopencode.controller.serviceAccountName" . }}
  namespace: {{ include "kubeopencode.namespace" . }}
  labels:
    {{- include "kubeopencode.controller.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
