apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeopencode.fullname" . }}-controller
  labels:
    {{- include "kubeopencode.controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeopencode.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ include "kubeopencode.controller.serviceAccountName" . }}
  namespace: {{ include "kubeopencode.namespace" . }}
