{{- if .Values.server.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeopencode.fullname" . }}-server
  labels:
    {{- include "kubeopencode.server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeopencode.fullname" . }}-server
subjects:
- kind: ServiceAccount
  name: {{ include "kubeopencode.server.serviceAccountName" . }}
  namespace: {{ include "kubeopencode.namespace" . }}
{{- end }}
