{{- if .Values.server.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeopencode.server.serviceAccountName" . }}
  namespace: {{ include "kubeopencode.namespace" . }}
  labels:
    {{- include "kubeopencode.server.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
