# Copyright Contributors to the KubeTask project
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubetask-dogfooding

resources:
  - workflow-go-update.yaml
  - webhooktrigger-github-pr-review.yaml
