# Copyright Contributors to the KubeOpenCode project
# Resources deployed to kubeopencode-system namespace.
# These support the Argo Events integration for webhook processing.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeopencode-system

resources:
  - deployment-smee-client.yaml
  - route-webhook.yaml
  - configmap-smee.yaml
