# Copyright Contributors to the KubeTask project
apiVersion: kubetask.io/v1alpha1
kind: Task
metadata:
  generateName: add-owners-
  namespace: kubetask-dogfooding
spec:
  # Use description field for simple task instructions
  description: |
    # Task: Add OWNERS File
    Add a OWNERS file with xuezhaojun name in for repo kubetask.
    Then push to GitHub and create a PR.
  contexts:
    - inline:
        type: Git
        mountPath: kubetask
        git:
          repository: https://github.com/kubetask-io/kubetask
          ref: main
